In [1]:
import torch
from gpt import SimpleMultiHeadAttention as SMHA
from gpt import LLMConfig as Cfg
from utils import set_seed

In [2]:
set_seed(0)

In [3]:
vocab_size=10
n_batch = 3
n_context = 5
n_embed = 6
n_heads=3

In [4]:
cfg = Cfg(
    n_vocab=vocab_size,
    n_context=n_context,
    n_embed=n_embed,
    n_heads=n_heads
    )

In [5]:
ssa = SMHA(cfg)
x = torch.randn((n_batch, n_context, n_embed))

In [6]:
x.shape

torch.Size([3, 5, 6])

In [7]:
ssa.Wqkv.weight.shape

torch.Size([18, 6])

In [8]:
x

tensor([[[-0.8025, -1.2952, -0.7502, -1.3120, -0.2188, -2.4351],
         [-0.0729, -0.0340,  0.7969, -0.1848, -0.3701, -1.2103],
         [-0.6227, -0.4637,  1.9218, -0.4025,  0.0930, -0.6661],
         [ 0.6080, -0.7300, -0.8834, -0.4189, -0.8048,  0.5656],
         [ 0.1804,  0.1083, -0.7548,  0.2443, -0.0773,  0.1164]],

        [[-0.5940, -1.2439, -0.0250,  1.3694,  2.6570,  0.9851],
         [-0.2596,  0.1183,  0.2440,  1.1646,  2.6963,  1.2358],
         [ 0.5428,  0.5255,  0.1922, -0.7722, -1.9003,  0.1307],
         [-1.6115, -0.4794, -0.1434, -0.3173,  0.9671, -0.9911],
         [ 0.3016, -0.1073,  0.8629, -0.0195,  0.9910, -0.7777]],

        [[ 0.3140,  0.2133, -0.1201,  0.3605, -2.3217, -1.1964],
         [ 0.1970, -1.1773, -0.0661, -0.3584, -1.5616, -0.3546],
         [-0.8137,  0.9242, -0.2871,  1.0216, -0.5111, -1.7137],
         [-0.5101, -0.4749, -0.6334, -1.4677,  0.6074, -0.5472],
         [-1.1005, -0.7201,  0.0119,  0.3398, -0.2635,  1.2805]]])

In [9]:
ssa.Wqkv.weight

Parameter containing:
tensor([[-0.0031,  0.2190, -0.3360, -0.3004, -0.1572,  0.1095],
        [-0.0081,  0.3237, -0.0362,  0.1080, -0.1234, -0.0802],
        [-0.3900, -0.2704, -0.1683,  0.0151,  0.1614,  0.2450],
        [-0.2768, -0.1778,  0.1483,  0.3390, -0.0840,  0.3055],
        [-0.0658,  0.0432,  0.3697, -0.3787, -0.2570, -0.1034],
        [-0.1591,  0.3527, -0.2646, -0.1879, -0.2852, -0.3823],
        [-0.2383,  0.3509,  0.1822,  0.1979,  0.0215, -0.2093],
        [ 0.0691, -0.3812, -0.2950, -0.2105,  0.2576,  0.2394],
        [-0.1811, -0.0147,  0.2611,  0.4059,  0.1620,  0.0552],
        [ 0.2737, -0.2404,  0.0761, -0.3165, -0.2830, -0.2109],
        [ 0.1847,  0.1642, -0.2418,  0.1233,  0.2241, -0.0515],
        [ 0.0156,  0.0946,  0.2533,  0.3920, -0.3146, -0.1496],
        [ 0.1604,  0.3383,  0.3553,  0.3602,  0.0812, -0.3550],
        [ 0.0376, -0.2554, -0.3805,  0.3627,  0.3104, -0.4072],
        [ 0.0764, -0.0688, -0.0672, -0.1869,  0.1570, -0.2418],
        [ 0.1497, 

In [10]:
q,k,v,qkt = ssa.forward(x)

In [11]:
q.shape

torch.Size([3, 3, 5, 2])

In [12]:
q[0]

tensor([[[ 0.1329, -0.3049],
         [-0.2937,  0.0835],
         [-0.7120, -0.2162],
         [ 0.4494, -0.2006],
         [ 0.2283,  0.0875]],

        [[ 0.1378, -0.8292],
         [-0.4555, -0.2569],
         [-0.1094,  0.1920],
         [ 0.1112, -0.0711],
         [ 0.0471, -0.0562]],

        [[ 0.5243,  1.1094],
         [ 0.5881,  0.3918],
         [ 0.9288, -0.2692],
         [-0.0911, -0.0285],
         [-0.3709,  0.1409]]], grad_fn=<SelectBackward0>)

In [13]:
qkt1 = q @ k.transpose(2,3) 

In [14]:
qkt1.shape

torch.Size([3, 3, 5, 5])

In [16]:
qkt[0]

tensor([[[-4.5285e-02,  9.0856e-02,  8.1800e-02, -1.1667e-01, -2.5232e-02],
         [ 2.8645e-02, -6.2652e-02, -6.4173e-02,  1.1397e-01,  1.9536e-02],
         [ 1.8761e-02, -5.3868e-02, -7.2830e-02,  1.7418e-01,  2.1654e-02],
         [-5.2632e-02,  1.1288e-01,  1.1256e-01, -1.9210e-01, -3.4355e-02],
         [-3.8101e-03,  1.3008e-02,  1.9753e-02, -5.1409e-02, -5.8246e-03]],

        [[-3.8834e-01, -1.5706e-01, -8.6763e-02, -2.0829e-01,  3.0842e-02],
         [ 2.8895e-02, -5.2738e-02, -1.1562e-01,  5.7330e-02,  3.7681e-02],
         [ 1.1314e-01,  3.5732e-02,  6.2804e-03,  6.7191e-02, -2.7645e-03],
         [-6.3073e-02, -1.2655e-02,  1.0265e-02, -4.2176e-02, -2.9670e-03],
         [-3.7649e-02, -1.0341e-02,  8.4551e-04, -2.3365e-02, -4.1342e-05]],

        [[-2.4064e-01,  1.3675e-01,  1.7381e-02, -1.3813e-01,  1.7307e-02],
         [-1.2856e-01,  6.3250e-03, -1.0085e-01, -5.7847e-02,  4.5666e-02],
         [-5.5787e-02, -1.4318e-01, -2.8460e-01,  9.7630e-03,  9.9457e-02],
        